configuration:
  groups:

    - name: GLOBAL_ISIS_DEFAULTS
      protocols:
        isis:
          interface:
            - hello_padding_type: disable
              name: <*>
          level:
            - disable: null
              name: '1'
            - name: '2'
              wide_metrics_only: null
          reference_bandwidth: 1000g
