---
provider_info:
  host: "{{ inventory_hostname }}"
  user: nornir
  passwd: "nornir123"
  # ssh_private_key_file: "~/.ssh/ansible_awx_tower"
# ansible_python_interpreter: "/opt/app-root/bin/python"
netbox_token: "1c47f23908e90acdced7ab0cb5ae37d66b93cf53"
netbox_url: "netbox:8080"
