# configuration:
#   system:
#     services:
#       outbound_ssh:
#         client: 
#           - name: "mist"
#             device_id: "{{ device.mist.id }}"
#             secret: "{{ device.mist.secret }}"
#             keep_alive:
#               retry: '3'
#               timeout: '5'
#             services: netconf
#             servers: 
#               - name: "oc-term.mistsys.net"
#                 port: '2200'
#                 retry: '1000'
#                 timeout: '60'
