configuration:
  policy_options:
    policy_statement:
      - name: LOOPBACK0
        from:
          prefix_list:
            name: PREFIX_LOOPBACK_0_IPV4
        then:
          accept: null
      - name: LOOPBACK1
        from:
          prefix_list:
            name: PREFIX_LOOPBACK_1_IPV4
        then:
          accept: null
      - name: POLICY_EXPORT_ROUTER_IPV4
        from:
          prefix_list:
            name: PREFIX_ROUTER_IPV4
        then:
          accept: null
      - name: POLICY_NEXT_HOP_SELF
        term:
          from:
            rib: inet.0
            route_type: external
          name: NHS
          then:
            next_hop:
              self: null
      - name: POLICY_DEFAULT
        from:
          protocol: access-internal
        then:
          accept: null
