---
all:
  children:
    pod1:
      children:
        spine:
          hosts:
            pod1-spine1:
              ansible_host: "10.6.6.101"
            pod1-spine2:
              ansible_host: "10.6.6.102"
        leaf:
          hosts:
            pod1-leaf1:
              ansible_host: "10.6.6.111"
            pod1-leaf2:
              ansible_host: "10.6.6.112"
            pod1-leaf3:
              ansible_host: "10.6.6.113"
            pod1-leaf4:
              ansible_host: "10.6.6.114"
